name: Build & Code Quality Checks
on:
  pull_request:
    branches: ['main', 'develop']
    types: ['opened', 'reopened', 'synchronize']

jobs:
  build:
    name: Build & Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Execute quality checks
        env:
          HUSKY: 0
        run: |
          npm ci
          npm run check:lint
          npm run check:circular
          npm run check:duplicates
          npm run check:security

      - name: Execute build
        env:
          HUSKY: 0
        run: |
          npm ci
          npm run build

      - name: Execute bundle size checks
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: check:size
