name: Deploy to DEV

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
    types:
      - closed

permissions:
  id-token: write # allows the JWT to be requested from GitHub's OIDC provider
  contents: read  # This is required for actions/checkout

jobs:
  deploy-tag:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/develop') || startsWith(github.ref, 'refs/heads/hotfix/') || github.event.pull_request.merged == true
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_DEV_ACCOUNT_ID }}:role/${{ secrets.AWS_DEV_S3_SYNC_ROLE }}
          aws-region: us-east-1

      - name: Checkout source branch
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Build and sync files to S3
        env:
          HUSKY: 0
        run: |
          npm ci
          npm run build:dev
          aws s3 cp dist/ s3://${{ secrets.AWS_DEV_S3_BUCKET_NAME }}/adapters/sp/beta/v1/dev --recursive --cache-control max-age=3600
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DEV_CF_DISTRIBUTION_ID }} --paths "adapters/sp/beta/v1/dev/rs-sp-analytics-staging.min.js" "adapters/sp/beta/v1/dev/rs-sp-analytics-staging.min.js.map"
