name: Deploy to PROD

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types:
      - closed

permissions:
  id-token: write # allows the JWT to be requested from GitHub's OIDC provider
  contents: read  # This is required for actions/checkout

jobs:
  deploy-tag:
    name: Deploy to PROD
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/main') || github.event.pull_request.merged == true
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_PROD_ACCOUNT_ID }}:role/${{ secrets.AWS_PROD_S3_SYNC_ROLE }}
          aws-region: us-east-1

      - name: Checkout source branch
        uses: actions/checkout@v3

      - name: Set Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Build and sync files to S3
        env:
          HUSKY: 0
        run: |
          npm ci
          npm run build
          aws s3 cp ./dist s3://${{ secrets.AWS_PROD_S3_BUCKET_NAME }}/adapters/sp/beta/v1 --acl public-read --cache-control max-age=3600
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "adapters/sp/beta/v1/rs-sp-analytics.min.js" "adapters/sp/beta/v1/rs-sp-analytics.min.js.map"
