name: 'Unit Tests, Coverage & Sonar'

on:
  workflow_dispatch:
  pull_request:
    branches: ['main', 'develop']
    types: ['opened', 'reopened', 'synchronize']

jobs:
  build:
    name: 'Unit Tests, Coverage & Sonar'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Execute unit tests
        env:
          HUSKY: 0
        run: |
          npm ci
          npm run test:ci
          npm run check:lint

      - name: Fix filesystem paths in generated reports
        run: |
          sed -i 's+home/runner/work/rudder-snowplow-migrator-js-sdk/rudder-snowplow-migrator-js-sdk+.+g' reports/coverage/lcov.info
          sed -i 's+/home/runner/work/rudder-snowplow-migrator-js-sdk/rudder-snowplow-migrator-js-sdk+/github/workspace+g' reports/eslint.json
          cat reports/coverage/lcov.info

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
