name: 'Tests & Coverage'
on:
  pull_request:
    branches: ['main', 'develop']
    types: ['opened', 'reopened', 'synchronize']

jobs:
  build:
    name: 'Tests & Coverage'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Execute unit tests
        env:
          HUSKY: 0
        run: |
          npm ci
          npm run test:ci
